# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- ea-frontsrv

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'Frontend Server app install'
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/AppServiceEasyAuth/FrontendNodejs'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact for Frontend Server app'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/AppServiceEasyAuth/FrontendNodejs'
    ArtifactName: 'frontsrv'
    publishLocation: 'Container'

#- script: |
#    npm install
#    npm run build
#  displayName: 'npm install and build'
